config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todos
  # get "home/index"
  root "home#index"
  get "home/about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todos_path }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  def quickupdate
    respond_to do |format|
      if @todo.quickupdate(todo_params)
        format.html 
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy!

    respond_to do |format|
      format.html { redirect_to todos_path, status: :see_other, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.expect(todo: [ :task, :status, :user_id ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/_footer.html.erb
<nav class="navbar bg-body-secondary" data-bs-theme="light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="/images/Motorcycle-line-art.jpg" alt="Logo" width="60" height="40" class="d-inline-block align-text-top">
      Footer
    </a>
  </div>
</nav>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-secondary" data-bs-theme="dark">
  <div class="container-fluid">
  	<%= link_to "Samu's Ruby on Rails Test", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About Me", home_about_path, class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to "To-Do", todos_path, class:"nav-link"%>
        </li>
        <li class="nav-item d-flex">
          <div class="dropdown">
            <button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account
            </button>
            <% if user_signed_in? %>
              <ul class="dropdown-menu dropdown-menu-end dropdown-menu-dark">
                <li><%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link"%></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, data: {turbo_method: :delete}, class:"nav-link"%></li>
                
              </ul>
            <% else %>
              <ul class="dropdown-menu dropdown-menu-end dropdown-menu-dark">
                <li class="nav-item"><%= link_to "Sign In", new_user_session_path, class:"nav-link"%></li>
              </ul>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div id="carouselExample" class="carousel slide">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="/images/bild-1.jpeg" class="d-block w-100" alt="Penis">
    </div>
    <div class="carousel-item">
      <img src="/images/bild-2.jpeg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="/images/bild-3.jpeg" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/home/index.html.erb
<h1>Hallo</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Rails Test</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>  
  </head>
  <body>
    <%= render "home/header"%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>   
    <div class="container border rounded-4 overflow-hidden">
      <%= yield %>
    </div>
    <br>
    <%= render "home/footer"%>
  </body>
</html> 

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :task, style: "display: block" %>
    <%= form.text_field :task %>
    <%= form.number_field :user_id, id: :todo_user_id, value: current_user.id%>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<div id="<%= dom_id todo %>">
  <p>
    <strong>Task:</strong>
    <%= todo.task %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= todo.status%>
  </p>

</div>

app/views/todos/edit.html.erb
<% content_for :title, "Editing todo" %>

<h1>Editing todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Back to todos", todos_path %>
</div>

app/views/todos/index.html.erb
<% content_for :title, "Todos" %>

<h1 class="display-1">To-Do List</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Task</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td>
          <p class="NoPaddingOrMargin fs-5">
            <%= todo.task %>
            <button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#<%= dom_id todo%>">
              <img src="/images/edit.png", height=28, class="imghoverable">
            </button>
          </p>
          

        <div class="modal fade" id="<%= dom_id todo%>" tabindex="-1" aria-labelledby="editModal" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="editModal">Editing todo</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <%= render "form", todo: todo%>
              </div>
            </div>
          </div>
        </div>

        </td>
      
        <td>
        <p class="NoPaddingOrMargin">
          <%= simple_form_for todo do |f|%>
            <%= f.input :status, as: :boolean, label: false, :input_html => {:onchange => "this.form.requestSubmit()", :style=>"height: 20px; width: 20px"}%>
          <% end %>
        </p>
        </td>
      </tr>

        
    <% end %>
  </tbody>
</table>

<%= link_to "New todo", new_todo_path, class:"btn btn-secondary"%>
<br>
<br>

app/views/todos/new.html.erb
<% content_for :title, "New todo" %>

<h1>New todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Back to todos", todos_path %>
</div>

app/views/todos/show.html.erb
<%= render @todo %>

<div>
  <%= link_to "Edit this todo", edit_todo_path(@todo) %> |
  <%= link_to "Back to todos", todos_path %>

  <%= button_to "Destroy this todo", @todo, method: :delete %>
</div>